manifest:
  projects:
    - name: zephyr
      url: https://github.com/mjaun/zephyr
      revision: zephyr-workshop
      import:
        path-prefix: external
        name-allowlist:
          - cmsis_6
          - picolibc
          - segger
          - hal_stm32
          - hal_st
