manifest:
  projects:
    - name: zephyr
      url: https://github.com/mjaun/zephyr
      revision: zephyr-workshop
      import:
        path-prefix: external
        name-allowlist:
          - cmsis_6
          - picolibc
          - segger
          - hal_stm32
          - hal_st

    - name: googletest
      url: https://github.com/google/googletest
      revision: v1.17.0
      path: external/googletest
